version: "3.9"

services:
  webserver:
    image: ngnix:latest
    restart: always
    environment:
      - name=value
    ports:
      - "80:80"
      - "443:433"
    volumes:
      - ./ngnix/conf/:/etc/ngnix/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
    networks:
      - backend
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
    networks:
      - backend
    
networks:
  backend:
