version: "3.9"

services:
  cobolweb:
    build: ./nodecobc
    restart: on-failure
    ports: 
      - "8080:8080"
    volumes: 
      - "./nodecobc:/usr/src/app/"
    network_mode: "host"
